baseurl = "/"
googleAnalytics = ""
languageCode = "ru-ru"
theme = "ooods"
title = "«Деловое сотрудничество», продюсерский центр"
[params]
custom_css = []
custom_js = []
description = "продюсерский центр «Деловое сотрудничество»"
disablefonts = false
name = "Деловое сотрудничество"
[params.about]
enable = true
endpoint = "У нас серьезные планы на будущее!"
subtitle = "Компания была организована в 1999 году группой журналистов, редакторов, режиссеров ТВ, работавших в то время на студии государственного телевидения. "
title = "О нас"
[[params.about.events]]
date = "1999"
description = "Мы участвовали во многих социальных проектах, производили социальные рекламные видеоролики, снимали социальной тематики сюжеты и фильмы. "
img = "1.jpg"
title = "Автономная Некоммерческая Организация"
[[params.about.events]]
date = "2002-2003"
description = "Два фильма о реабилитации страдающих хроническими психическими заболеваниями (фильм «Эссенские контакты» снимался нами в Германии по приглашению немецкой стороны в 2003 году)"
img = "2.jpg"
title = "фильм «Эссенские контакты»"
[[params.about.events]]
date = "2002 год"
description = "По инициативе «Делового сотрудничества» в 2002 году был снят фильм, предназначенный для родителей школьников, в котором рассказывалось о первых признаках наркотической зависимости. Этот фильм получил высокую оценку у врачей и педагогов, был рекомендован для показа в школах Нижегородской области. Наш «антинаркотический» видеоролик был удостоен первой премии на конкурсе социальной рекламы, проводимом Правительством Нижегородской области."
img = "3.jpg"
title = "Фильм о наркомании для школьников"
[[params.about.events]]
date = "2003-2005"
description = "На протяжении двух лет мы выпускали в эфире телеканала «Вести 24» еженедельную программу «Таможенные вести» и были отмечены Первой премией, учрежденной Приволжским федеральным таможенным управлением."
img = "4.jpg"
title = "«Таможенные вести», телеканал «Россия 24»"
[[params.about.events]]
date = "2005-2008"
description = "ПЦ «Деловое сотрудничество» являлось региональным вещателем Общественного Российского радио в Нижнем Новгороде. «ОРР в НН» на волне 106.4 FM — одна из немногих радиостанций в эфире Нижнего Новгорода, программы которой носили разговорный, а не чисто музыкальный характер. У нас была устойчивая аудитория, состоящая преимущественно из людей от 30 лет и старше."
img = "4.jpg"
title = "ПЦ «Деловое сотрудничество»"
[[params.about.events]]
date = "2008-2014"
description = "«Деловое сотрудничество» выпускает программу «Социальные вести» (часть программ — по заказу Правительства Нижегородской области). Задачи программы — информировать зрителей о важнейших событиях в социальной сфере региона. Разъяснять положения важнейших законов, знания которых позволяют улучшить жизнь людей. Отвечать на возникающие у зрителей вопросы, привлекая соответствующих чиновников и специалистов. Разъяснять зрителям их права и обязанности в социальной сфере (трудовое законодательство, семейный кодекс, пенсионное законодательство и др.)."
img = "4.jpg"
title = " «Социальные вести»"
[[params.about.events]]
date = "с 2014 года"
description = "У нас есть серьезные планы на будущее. Прежде всего, они связаны с развитием телевизионного направления нашей деятельности. Один из крупных и пока не осуществленных проектов — создание полноценной студии документальных фильмов."
img = "4.jpg"
title = "Развитием телевизионного направления"
[params.clients_list]
enable = true
[params.contact]
buttontext = "Отправить"
email = "your@email.com"
enable = true
subtitle = "."
title = "Связаться с нами"
[params.contact.form.email]
text = "Email *"
warning = "Адрес электронной почты."
[params.contact.form.message]
text = "Сообщение *"
warning = "Ваше сообщение."
[params.contact.form.name]
text = "Ваше имя *"
warning = "Представьтесь, пожалуйста."
[params.contact.form.phone]
text = "Телефон *"
warning = "Ваш номер телефона."
[params.error404]
heading = "Страница не найдена"
text = "Перейти на [главную](/)"
[params.footer]
copyright = "."
enable = false
[[params.footer.quicklinks]]
link = "#"
text = "Privacy Policy"
[[params.footer.quicklinks]]
link = "#"
text = "Terms of Use"
[[params.footer.social]]
icon = "fa-twitter"
link = "#"
title = "Twitter"
[[params.footer.social]]
icon = "fa-facebook"
link = "#"
title = "Facebook"
[[params.footer.social]]
icon = "fa-linkedin"
link = "#"
title = "LinkedIn"
[params.hero]
buttontext = "Далее"
subtitle = "«Деловое сотрудничество»"
title = "продюсерский центр "
[params.navigation]
about = "О нас"
brand = "продюсерский центр «Деловое сотрудничество»"
contact = "Контакты"
logo = "ooods.min.svg"
portfolio = "Портфолио"
services = "Услуги"
[params.portfolio]
enable = true
subtitle = "."
title = "Портфолио"
[params.portfolio.modal]
buttontext = "Закрыть проект"
category = "Категоря"
client = "Клиент"
date = "Дата"
[params.services]
enable = true
subtitle = "Lorem ipsum dolor sit amet consectetur."
title = "Услуги"
[[params.services.row]]
[[params.services.row.list]]
description = "Производство видеофильмов, Производство видеосъемок и монтаж видео, Производство видео для Интернет сайтов"
icon = "fa-lock"
title = "Видео"
url = "services-video"
[[params.services.row.list]]
description = "Производство ТВ-программ, Производство ТВ-сюжетов, Производство ТВ-рекламы."
icon = "fa-lock"
title = "ТВ"
url = "services-tv"
[[params.services.row.list]]
description = "Производство видео для Интернет сайтов, Создание и ведение Интернет-сайтов, СММ, СЕО"
icon = "fa-lock"
title = "Веб услуги"
url = "services-web"
[[params.services.row.list]]
description = "Разработка логотипов. Создание и предпечатная подготовка графики"
icon = "fa-lock"
title = "Дизайн"
url = "services-design"
[[params.services.row.list]]
description = "Производство радиопрограмм. Производство аудиорекламы."
icon = "fa-lock"
title = "Реклама"
url = "services-advertising"
[[params.services.row.list]]
description = "Репутационный и электоральный консалтин."
icon = "fa-lock"
title = "Консалтинг"
url = "services-consulting.html"
[params.team]
description = "."
enable = true
subtitle = "."
title = "Наша комманда"
[[params.team.members]]
img = "man.png"
name = "Алексей Скульский"
position = "основатель и учредитель"
[[params.team.members]]
img = "man.png"
name = "Сергей Вострилов"
position = "основатель и учредитель"
