---
hide_body: false
is_partial: false
fields:
- name: title
  label: Заголовок
  type: text
  hidden: false
  default: 
  config:
    required: true
- type: datetime
  default: Invalid date
  label: Date
  name: date
  hidden: true
  config:
    required: false
- name: type
  label: Type
  type: text
  hidden: true
  default: page
  config:
    required: true
