---
label: services
hide_body: false
is_partial: false
fields:
- name: title
  label: Заголовок
  type: text
  hidden: false
  default: 
  config:
    required: true
- type: datetime
  default: Invalid date
  label: Date
  name: date
  hidden: true
  config:
    required: false
- name: type
  label: Type
  type: text
  hidden: true
  default: page
  config:
    required: true
pages:
- content/services/design.md
- content/services/consulting.md
- content/services/tv.md
- content/services/advertising.md
- content/services/web.md
- content/services/video.md
